### ISSUE TITLE
CI is broken on Py2.7

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/fasm#16]
Most recent CI is failing on Py2.7.  Given that Py2 is [sunsetting](https://www.python.org/doc/sunset-python-2/), it may be time to just drop support.

**Comment by litghost** [comment]
@mithro ?

**Comment by mithro** [comment]
I'm okay with dropping 2.7 support...

**Comment by litghost** [comment]
Py 2.7 on CI removed in https://github.com/SymbiFlow/fasm/pull/17
