### ISSUE TITLE
Add link in the documentation header to the SymbiFlow project

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/fasm#26]
![Screenshot from 2020-04-28 21-41-50](https://user-images.githubusercontent.com/21212/80561375-1c898e80-8999-11ea-9457-b96e069d401a.png)

In the `Home` / `GitHub` link section, we should add;
 - Links to the SymbiFlow website
 - Links to the SymbiFlow readthedocs documentation.

Anything else?

**Comment by mithro** [comment]
@daniellimws - Might be worth seeing if this needs to be done on the other documentation sites?

**Comment by daniellimws** [comment]
I think we can add these links through the symbiflow theme (with an option to disable), so that it applies to all that uses it by default.

**Comment by mithro** [comment]
Sounds good to me!
