### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/fasm#32]
After https://github.com/SymbiFlow/fasm/pull/28

**Comment by mithro** [comment]
I'm slowly getting there now, see my WIP pull request at https://github.com/SymbiFlow/fasm/pull/48/files 

 - https://github.com/mithro/fasm/runs/1836865327?check_suite_focus=true
![Screenshot from 2021-02-04 23-01-04](https://user-images.githubusercontent.com/21212/107000533-e6094d00-673c-11eb-8674-dc1f615ac16c.png)
![Screenshot from 2021-02-04 23-01-29](https://user-images.githubusercontent.com/21212/107000571-f02b4b80-673c-11eb-897c-6b93dd707598.png)

The Windows build continues to have issues with ANTLR

**Comment by mithro** [comment]
This is now happening.
