### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zipotron** [SymbiFlow/fasm#90]
Hello, I am trying to compile and install but I found this error following the compiling steps:
![ccc](https://user-images.githubusercontent.com/6671137/182838059-94d95000-8de1-4d2b-83be-6156ef1f9ec0.png)
![error](https://user-images.githubusercontent.com/6671137/182838064-a383f037-d688-402b-ad4b-a0ba484bdcd7.png)

**Comment by pgielda** [comment]
As for the first screenshot -- looking at the output it seems that you do not have Cython installed? If its a debian or debian derivative distro, maybe try `sudo apt install cython` and then try again?

As for the second one I will let @kgugala answer

**Comment by zipotron** [comment]
Works perfectly! Thanks!
